# Generated by Django 4.1.7 on 2023-02-22 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratetourismplace',
            old_name='TourismPlace',
            new_name='tourismPlace',
        ),
        migrations.AlterUniqueTogether(
            name='ratehotel',
            unique_together={('user', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='ratetourismplace',
            unique_together={('user', 'tourismPlace')},
        ),
        migrations.AlterIndexTogether(
            name='ratehotel',
            index_together={('user', 'hotel')},
        ),
        migrations.AlterIndexTogether(
            name='ratetourismplace',
            index_together={('user', 'tourismPlace')},
        ),
    ]
