# Generated by Django 4.1.7 on 2023-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0002_rename_tourismplace_ratetourismplace_tourismplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
