# Generated by Django 4.1.7 on 2023-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_alter_tourismplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
