# Generated by Django 4.1.7 on 2023-02-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_alter_tourismplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='image',
            field=models.ImageField(upload_to='photo/%y/%m/%d'),
        ),
    ]
