# Generated by Django 4.1.7 on 2023-02-23 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0005_alter_tourismplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratehotel',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ratetourismplace',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
