# Generated by Django 4.1.7 on 2023-02-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0010_remove_hotel_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratehotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average', to='Tourism.hotel'),
        ),
    ]
